name: wise_bluetooth_print
description: A new flutter plugin project to get print out from bluetooth printers for Android.
version: 0.0.1
homepage: https://github.com/kaanakyalcin/wise_bluetooth_print

environment:
  sdk: ">=2.16.0 <3.0.0"
  flutter: ">=2.5.0"

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^1.0.0


flutter:
  plugin:
    platforms:
      android:
        package: com.example.wise_bluetooth_print
        pluginClass: WiseBluetoothPrintPlugin


