name: wise_bluetooth_print
description: minor bug fixes for Android 11
version: 0.0.2
homepage: https://github.com/kaanakyalcin/wise_bluetooth_print

environment:
  sdk: ">=2.16.0 <3.0.0"
  flutter: ">=2.5.0"

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^1.0.0


flutter:
  plugin:
    platforms:
      android:
        package: com.example.wise_bluetooth_print
        pluginClass: WiseBluetoothPrintPlugin


